EsercitazioneFinale.Cracco.MVC/Models/ErrorViewModel.cs
namespace EsercitazioneFinale.Cracco.MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EsercitazioneFinale.Cracco.MVC/Models/MenuViewModel.cs
using EsercitazioneFinale.Cracco.Core.Entities;
using System.ComponentModel.DataAnnotations;

namespace EsercitazioneFinale.Cracco.MVC.Models
{
    public class MenuViewModel
    {
        public int Id { get; set; }
        [Required]
        public string Nome { get; set; }
        public List<PiattoViewModel> Piatti { get; set; } = new List<PiattoViewModel>();
    }
}

EsercitazioneFinale.Cracco.MVC/Models/PiattoViewModel.cs
using EsercitazioneFinale.Cracco.Core.Entities;
using System.ComponentModel.DataAnnotations;
using static EsercitazioneFinale.Cracco.Core.Entities.Piatto;

namespace EsercitazioneFinale.Cracco.MVC.Models
{
    public class PiattoViewModel
    {
        public int Id { get; set; }
        [Required]
        public string Nome { get; set; }
        public string? Descrizione { get; set; }
        [Required]
        public double Prezzo { get; set; }
        [Required]
        public Tipologia Tipo { get; set; }
        public int? MenuId { get; set; }
        public Menu? Menu { get; set; }
    }
}

EsercitazioneFinale.Cracco.MVC/Models/UserViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace EsercitazioneFinale.Cracco.MVC.Models
{
    public class UserViewModel
    {
        [Required]
        public string UserName { get; set; }
        [Required, DataType(DataType.Password)]
        public string Password { get; set; }   
        public string ReturnUrl { get; set; }
    }
}

EsercitazioneFinale.Cracco.MVC/Controllers/HomeController.cs
using EsercitazioneFinale.Cracco.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EsercitazioneFinale.Cracco.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EsercitazioneFinale.Cracco.MVC/Controllers/MenuController.cs
using EsercitazioneFinale.Cracco.Core.Entities;
using EsercitazioneFinale.Cracco.Core.Interfaces;
using EsercitazioneFinale.Cracco.MVC.Mapping;
using EsercitazioneFinale.Cracco.MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace EsercitazioneFinale.Cracco.MVC.Controllers
{
    public class MenuController : Controller
    {
        private readonly IBusinessLayer BL;

        public MenuController(IBusinessLayer bL)
        {
            BL = bL;
        }

        [HttpGet]
        public IActionResult Index()
        {
            List<Menu> menu = BL.GetAllMenu();
            List<MenuViewModel> menuViewModel = new List<MenuViewModel>();
            foreach(var item in menu)
            {
                menuViewModel.Add(item.ToMenuViewModel());
            }
            return View(menuViewModel);
        }
        [HttpGet]
        public IActionResult Details(int id)
        {
            var menu = BL.GetMenuById(id);
            var piatti = menu.Piatti.ToList();
            var piattiViewModel = new List<PiattoViewModel>();
            double PrezzoTotale = 0;
            foreach (var item in piatti)
            {
                piattiViewModel.Add(item.ToPiattoViewModel());
                PrezzoTotale += item.Prezzo;
            }
            ViewBag.PrezzoTotale=PrezzoTotale;
            ViewBag.NomeMenu = menu.Nome;
            return View(piattiViewModel);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(MenuViewModel menuViewModel)
        {
            if(ModelState.IsValid)
            {
                Menu menu = menuViewModel.ToMenu();
                Esito esito = BL.AddMenu(menu);
                if (esito.IsOK)
                    return RedirectToAction("Index");
                else
                {
                    ViewBag.ErrorMex = esito.Mex;
                    return View("BusinessError");
                }
            }
            return View(menuViewModel);
        }
    }
}

EsercitazioneFinale.Cracco.MVC/Controllers/PiattiController.cs
using EsercitazioneFinale.Cracco.Core.Entities;
using EsercitazioneFinale.Cracco.Core.Interfaces;
using EsercitazioneFinale.Cracco.MVC.Mapping;
using EsercitazioneFinale.Cracco.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using static EsercitazioneFinale.Cracco.Core.Entities.Piatto;

namespace EsercitazioneFinale.Cracco.MVC.Controllers
{
    public class PiattiController : Controller
    {
        private readonly IBusinessLayer BL;

        public PiattiController(IBusinessLayer bl)
        {
            BL = bl;
        }
        public IActionResult Index()
        {
            var piatti = BL.GetAllPiatti();
            List<PiattoViewModel> piattoViewModel = new List<PiattoViewModel>();
            foreach (var piatto in piatti)
            {
                piattoViewModel.Add(piatto.ToPiattoViewModel());
            }
            return View(piattoViewModel);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(PiattoViewModel piattoViewModel)
        {
            if(ModelState.IsValid)
            {
                //Assegnazione dell'id tramite il nome del menu inserito dall'utente
                var menu = BL.GetAllMenu().FirstOrDefault(m=>m.Nome == piattoViewModel.Menu.Nome);
                piattoViewModel.MenuId = menu.Id;

                var piatto = piattoViewModel.ToPiatto();
                var esito = BL.AddPiatto(piatto);
                if(esito.IsOK)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewBag.ErroMex = esito.Mex;
                    return View("BusinessError");
                }
            }
            
            return View(piattoViewModel);
        }
        [HttpGet]
        public IActionResult Update(int id)
        {
           
            var piatto = BL.GetPiattoById(id);
            var piattoViewModel = piatto.ToPiattoViewModel();
            return View(piattoViewModel);
        }
        [HttpPost]
        public IActionResult Update(PiattoViewModel piattoViewModel)
        {
            if (ModelState.IsValid)
            {
                //Assegnazione dell'id tramite il nome del menu inserito dall'utente
                var menu = BL.GetAllMenu().FirstOrDefault(m => m.Nome == piattoViewModel.Menu.Nome);
                piattoViewModel.MenuId = menu.Id;
               
                var piatto = piattoViewModel.ToPiatto();
                var esito = BL.UpdatePiatto(piatto);
                if (esito.IsOK)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewBag.ErroMex = esito.Mex;
                    return View("BusinessError");
                }
            }
            
            return View(piattoViewModel);
        }
        [HttpGet]
        public IActionResult Delete(PiattoViewModel piattoViewModel)
        {
            var piatto = piattoViewModel.ToPiatto();
            var esito = BL.DeletePiatto(piatto.Id);
            if (esito.IsOK)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewBag.ErrorMessage = esito.Mex;
                return View("BusinessError");
            }
        }
    }
}

EsercitazioneFinale.Cracco.MVC/Controllers/UserController.cs
using EsercitazioneFinale.Cracco.Core.Interfaces;
using EsercitazioneFinale.Cracco.MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace EsercitazioneFinale.Cracco.MVC.Controllers
{
    public class UserController : Controller
    {
        private readonly IBusinessLayer BL;
        public UserController(IBusinessLayer bl)
        {
            BL = bl;  
        }
        public IActionResult Login(string returnUrl="/")
        {
            return View(new UserViewModel { ReturnUrl=returnUrl});
        }
    }
}

EsercitazioneFinale.Cracco.MVC/Views/Contatti/Index.cshtml
<div>
    <h4>Contatti</h4><br />
    <h6>E-Mail: SonoIlMigliore@Cracco.io</h6>
    <h6>Tel: +39 1111111111</h6>
    @*<e-mail to-user="SonoIlMigliore@Cracco.io"></e-mail>*@
    <a class="btn btn-primary" href=mailto:SonoIlMigliore@Cracco.io>Mandami una e-mail</a>
</div>

EsercitazioneFinale.Cracco.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center" >
    <h1 class="Titolo" style="font-family:Papyrus; font-size:80px">Benvenuti da Cracco</h1><br />
    <p style="font-family:'Times New Roman', Times, serif">Il Ristorante migliore della tuo paese, città, regione, stato, continente, emisfero, mondo..UNIVERSO</a>.</p>
</div>

EsercitazioneFinale.Cracco.MVC/Views/Menu/Create.cshtml
@model MenuViewModel

<h2>Inserisci il nuovo Menu</h2>

<form method="post">
    <div class="form-group">
    <label asp-for="Nome"></label>
    <input asp-for="Nome" class="form-control" />
    <span asp-validation-for="Nome" class="text-danger"></span>
</div>
</form>

EsercitazioneFinale.Cracco.MVC/Views/Menu/Details.cshtml
@model List<PiattoViewModel>
<h3>Lista dei piatti del Menu @ViewBag.NomeMenu</h3>
<table class="table table-hover table-dark table-bordered opacity-75" style="color:whitesmoke  ">
    <partial name="_TablePiatti" model="Model"/>
    @*<thead>
        <tr style="color:black">
            <th>Nome</th>
            <th>Descrizione</th>
            <th>Prezzo</th>
            <th>Portata</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td>@item.Nome</td>
                <td>@item.Descrizione</td>
                <td>@item.Prezzo</td>
                <td>@item.Tipo</td>
            </tr>
        }*@
    </tbody>
    <tfoot>
        <tr>
            <th>Totale</th>
            <th>@ViewBag.PrezzoTotale - Euro</th>
            <th></th>
            <th></th>
        </tr>
    </tfoot>
</table>

EsercitazioneFinale.Cracco.MVC/Views/Menu/Index.cshtml
@model List<MenuViewModel>

<h2>Lista dei Menu in programma quest'anno</h2>
<a type=button class="btn btn-primary" asp-controller="Menu" asp-action="Create">Inserisci un nuovo Menu</a> 
<table class="table table-hover table-dark table-bordered opacity-75">
    <thead>
        <tr>
            <th>Nome</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td>@item.Nome</td>
                <td>
                    <a asp-controller="Menu" asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary">Visualizza i Piatti</a>
                </td>
            </tr>
        }
    </tbody>
</table>

EsercitazioneFinale.Cracco.MVC/Views/Piatti/Create.cshtml
@model PiattoViewModel

<h2>Inserisci i dati del piatto che vuoi inserire</h2>
<form method="post">
    <partial name="_InsertPiatti" model="Model" />

    <input type="submit" value="Inserisci" class="btn btn-primary" />
    <input type="reset" value="Clean" class="=btn btn-primary" />
    <a class="btn btn-primary" asp-controller="Piatti" asp-action="Index">Indietro</a>
</form>

EsercitazioneFinale.Cracco.MVC/Views/Piatti/Index.cshtml
@model List<PiattoViewModel>

<h2>Lista dei Piatti</h2>
<a type=button class="btn btn-primary" asp-controller="Piatti" asp-action="Create">Inserisci un nuovo Piatto</a> 

<table class="table table-hover table-dark table-bordered opacity-75" style="color:whitesmoke  ">
    <thead>
        <tr style="color:black">
            <th>Nome</th>
            <th>Descrizione</th>
            <th>Prezzo</th>
            <th>Portata</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td>@item.Nome</td>
                <td>@item.Nome</td>
                <td>@item.Descrizione</td>
                <td>@item.Prezzo</td>
                <td>@item.Tipo</td>
                <td>
                    <a asp-controller="Piatti" asp-action="Update" asp-route-id="@item.Id" class="btn btn-primary">Modifica</a>
                </td>
                <td>
                    <a asp-controller="Piatti" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-primary">Elimina</a>
                </td>
            </tr>
        }
    </tbody>
 </table>

EsercitazioneFinale.Cracco.MVC/Views/Piatti/Update.cshtml
@model PiattoViewModel

<form method ="post">
    <partial name="_InsertPiatti" model="Model" />

    <input type="submit" value="Aggiorna" class="btn btn-primary" />
    <input type="reset" value="Pulisci" class="=btn btn-primary" />
    <a class="btn btn-primary" asp-controller="Piatti" asp-action="Index">Indietro</a>
</form>

EsercitazioneFinale.Cracco.MVC/Views/Shared/BusinessError.cshtml
<p>@ViewBag.ErrorMex</p>

EsercitazioneFinale.Cracco.MVC/Views/Shared/_InsertPiatti.cshtml
@model PiattoViewModel

<div class="form-group">
    <label asp-for="Nome"></label>
    <input asp-for="Nome" class="form-control" />
    <span asp-validation-for ="Nome" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="Descrizione"></label>
    <input asp-for="Descrizione" class="form-control" />
</div>

<div class="form-group">
    <label asp-for="Prezzo"></label>
    <input asp-for="Prezzo" class="form-control" />
    <span asp-validation-for ="Prezzo" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="Tipo"></label>
    <select asp-for="Tipo" asp-items="@ViewBag.Portata" class="form-control">
        <option value="">Seleziona il tipo di portata</option>
        <option value="1">Primo</option>
        <option value="2">Secondo</option>
        <option value="3">Contorno</option>
        <option value="4">Dolce</option>

    </select>
    <span asp-validation-for ="Tipo" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="Menu.Nome"></label>
    <input asp-for="Menu.Nome" class="form-control" />
    <span asp-validation-for ="Menu.Nome" class="text-danger"></span>
</div>

EsercitazioneFinale.Cracco.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Da Cracco</title>
    <link rel="icon" href="/favicon.ico" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EsercitazioneFinale.Cracco.MVC.styles.css" asp-append-version="true" />
</head>
<body style="background-image: url(https://images.wired.it/wp-content/uploads/2016/02/1456744505_Carlo-Cracco.jpg);">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Da Cracco</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Menu" asp-action="Index">Menu</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Piatti" asp-action="Index">Piatti</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contatti" asp-action="Index">Contatti</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login">Login</a>
                    </li>
                </div>
                 
            </div>
           
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Da Cracco - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

EsercitazioneFinale.Cracco.MVC/Views/Shared/_TablePiatti.cshtml
@model List<PiattoViewModel>
<thead>
        <tr style="color:black">
            <th>Nome</th>
            <th>Descrizione</th>
            <th>Prezzo</th>
            <th>Portata</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td>@item.Nome</td>
                <td>@item.Descrizione</td>
                <td>@item.Prezzo</td>
                <td>@item.Tipo</td>
            </tr>
        }
    </tbody>

EsercitazioneFinale.Cracco.MVC/Views/User/Login.cshtml
<div class="login-page">
  <div class="form">
    <form class="register-form">
      <input type="text" placeholder="name"/>
      <input type="password" placeholder="password"/>
      <button>Registrati</button>
    </form>
    <form class="login-form">
      <input type="text" placeholder="username"/>
      <input type="password" placeholder="password"/>
      <button>Login</button>
    </form>
  </div>
</div>